#第四章  Numpy库基础<br>


In [6]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rcParams

rcParams['figure.facecolor']=(1,1,1,1)
rcParams['font.family']='simhei'
rcParams['font.size']=13

In [7]:
arr=np.array([1,2,4,5,6])
arr.dtype

dtype('int32')

In [8]:
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [9]:
numeric_strings=np.array(['1.25','3.45','5.65'],dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [10]:
new_num=numeric_strings.astype(float)
new_num.dtype

dtype('float64')

In [11]:
empty_arr=np.empty((2,3),dtype='u4')
empty_arr

array([[         0, 1072168960,          0],
       [1072168960,          0,          0]], dtype=uint32)

In [12]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [14]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [15]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [16]:
arr*0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [17]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
arr[5:8]

array([5, 6, 7])

In [19]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [20]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [21]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [22]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [24]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [25]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [28]:
names=np.array(['bob','joe','amy','will','joe','joe'])
names

array(['bob', 'joe', 'amy', 'will', 'joe', 'joe'],
      dtype='<U4')

In [29]:
data=np.random.randn(7,4)
data

array([[ 0.33810283, -1.86961196, -1.70547844,  1.0817089 ],
       [-1.4399714 , -0.05520173,  0.63306371, -0.40174033],
       [-1.10801835, -0.83824848,  0.06661057, -0.60843394],
       [ 0.32900883, -0.03534989,  0.4777522 , -1.68034261],
       [ 2.4295853 ,  1.19221271, -0.22809514, -0.86340546],
       [ 0.12057037,  0.27122704,  1.19149267, -0.41476841],
       [-0.36836542, -1.59061809,  0.88829883,  0.08656083]])

In [30]:
names=='bob'

array([ True, False, False, False, False, False], dtype=bool)

In [31]:
names=np.array(['bob','joe','bob','amy','will','joe','joe'])
names=='bob'

array([ True, False,  True, False, False, False, False], dtype=bool)

In [32]:
data[names=='bob']

array([[ 0.33810283, -1.86961196, -1.70547844,  1.0817089 ],
       [-1.10801835, -0.83824848,  0.06661057, -0.60843394]])

In [33]:
names!='bob'

array([False,  True, False,  True,  True,  True,  True], dtype=bool)

In [34]:
data[names!='bob']

array([[-1.4399714 , -0.05520173,  0.63306371, -0.40174033],
       [ 0.32900883, -0.03534989,  0.4777522 , -1.68034261],
       [ 2.4295853 ,  1.19221271, -0.22809514, -0.86340546],
       [ 0.12057037,  0.27122704,  1.19149267, -0.41476841],
       [-0.36836542, -1.59061809,  0.88829883,  0.08656083]])

In [35]:
names

array(['bob', 'joe', 'bob', 'amy', 'will', 'joe', 'joe'],
      dtype='<U4')

In [36]:
mask=(names=='bob') | (names=='will')
mask

array([ True, False,  True, False,  True, False, False], dtype=bool)

In [37]:
data[mask]

array([[ 0.33810283, -1.86961196, -1.70547844,  1.0817089 ],
       [-1.10801835, -0.83824848,  0.06661057, -0.60843394],
       [ 2.4295853 ,  1.19221271, -0.22809514, -0.86340546]])

In [38]:
data[mask]=0
data[mask]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [39]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [-1.4399714 , -0.05520173,  0.63306371, -0.40174033],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.32900883, -0.03534989,  0.4777522 , -1.68034261],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.12057037,  0.27122704,  1.19149267, -0.41476841],
       [-0.36836542, -1.59061809,  0.88829883,  0.08656083]])

In [40]:
data=np.random.randn(7,4)
data

array([[-0.35790825, -0.13956776,  1.00178583, -0.98239702],
       [-0.16241243, -0.07314511, -1.71902514,  2.44931958],
       [-0.18941901, -1.65561385, -0.43178634,  0.82444337],
       [ 0.28030609,  0.42407554,  0.39727374,  1.72186631],
       [ 2.02467289, -0.72471426,  0.66208802,  0.62104449],
       [ 1.1095835 ,  0.95193449,  1.60702609, -1.0467256 ],
       [ 0.49962356, -0.94798984,  0.59382849, -0.74584365]])

In [41]:
data[names=='bob']=7
data

array([[ 7.        ,  7.        ,  7.        ,  7.        ],
       [-0.16241243, -0.07314511, -1.71902514,  2.44931958],
       [ 7.        ,  7.        ,  7.        ,  7.        ],
       [ 0.28030609,  0.42407554,  0.39727374,  1.72186631],
       [ 2.02467289, -0.72471426,  0.66208802,  0.62104449],
       [ 1.1095835 ,  0.95193449,  1.60702609, -1.0467256 ],
       [ 0.49962356, -0.94798984,  0.59382849, -0.74584365]])

In [42]:
arr=np.empty((8,4))
arr

array([[  2.36163379e-321,   4.64173489e-317,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  2.59428811e-316,   0.00000000e+000,   6.70931416e-315,
          6.85003955e-316],
       [  6.84644117e-316,   6.84729847e-316,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   6.85090357e-316,   3.37359762e-316,
          6.70932380e-315],
       [  0.00000000e+000,   6.84644433e-316,   0.00000000e+000,
          6.70932665e-315],
       [  0.00000000e+000,   6.70805844e-315,   0.00000000e+000,
          8.65132266e-317],
       [  0.00000000e+000,   4.11807945e-316,   0.00000000e+000,
          6.70931416e-315]])

In [43]:
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [44]:
arr[[4,3,0,6]].shape

(4, 4)

In [45]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [46]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [47]:
arr[[1,5,7,2]][[0,3,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [48]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [49]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [50]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [61]:
nx,ny=(3,4)
x=np.linspace(0,2,nx)
y=np.linspace(3,6,ny)
x

array([ 0.,  1.,  2.])

In [62]:
y

array([ 3.,  4.,  5.,  6.])

In [63]:
xx,yy=np.meshgrid(x,y)
xx

array([[ 0.,  1.,  2.],
       [ 0.,  1.,  2.],
       [ 0.,  1.,  2.],
       [ 0.,  1.,  2.]])

In [64]:
yy

array([[ 3.,  3.,  3.],
       [ 4.,  4.,  4.],
       [ 5.,  5.,  5.],
       [ 6.,  6.,  6.]])

In [73]:
points=np.arange(-5,5,0.01)

In [74]:
xs,ys=np.meshgrid(points,points)

In [75]:
xs

array([[-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       ..., 
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99],
       [-5.  , -4.99, -4.98, ...,  4.97,  4.98,  4.99]])

In [76]:
ys

array([[-5.  , -5.  , -5.  , ..., -5.  , -5.  , -5.  ],
       [-4.99, -4.99, -4.99, ..., -4.99, -4.99, -4.99],
       [-4.98, -4.98, -4.98, ..., -4.98, -4.98, -4.98],
       ..., 
       [ 4.97,  4.97,  4.97, ...,  4.97,  4.97,  4.97],
       [ 4.98,  4.98,  4.98, ...,  4.98,  4.98,  4.98],
       [ 4.99,  4.99,  4.99, ...,  4.99,  4.99,  4.99]])

In [77]:
import matplotlib.pyplot as plt

In [78]:
z=np.sqrt(xs**2+ys**2)
z

array([[ 7.07106781,  7.06400028,  7.05693985, ...,  7.04988652,
         7.05693985,  7.06400028],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       ..., 
       [ 7.04988652,  7.04279774,  7.03571603, ...,  7.0286414 ,
         7.03571603,  7.04279774],
       [ 7.05693985,  7.04985815,  7.04278354, ...,  7.03571603,
         7.04278354,  7.04985815],
       [ 7.06400028,  7.05692568,  7.04985815, ...,  7.04279774,
         7.04985815,  7.05692568]])

In [ ]:
plt.imshow(z,cmap=plt.cm.gray)