#第四章  Numpy库基础<br>


In [3]:
import matplotlib.pyplot as plt
import numpy as np
from matplotlib import rcParams

rcParams['figure.facecolor']=(1,1,1,1)
rcParams['font.family']='simhei'
rcParams['font.size']=13

In [4]:
arr=np.array([1,2,4,5,6])
arr.dtype

dtype('int32')

In [5]:
float_arr=arr.astype(np.float64)
float_arr.dtype

dtype('float64')

In [6]:
numeric_strings=np.array(['1.25','3.45','5.65'],dtype=np.string_)
numeric_strings.dtype

dtype('S4')

In [7]:
new_num=numeric_strings.astype(float)
new_num.dtype

dtype('float64')

In [8]:
empty_arr=np.empty((2,3),dtype='u4')
empty_arr

array([[         0, 1072168960,          0],
       [1072168960,          0,          0]], dtype=uint32)

In [9]:
arr=np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [11]:
arr-arr

array([[0, 0, 0],
       [0, 0, 0]])

In [12]:
1/arr

array([[ 1.        ,  0.5       ,  0.33333333],
       [ 0.25      ,  0.2       ,  0.16666667]])

In [13]:
arr*0.5

array([[ 0.5,  1. ,  1.5],
       [ 2. ,  2.5,  3. ]])

In [14]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr[5:8]

array([5, 6, 7])

In [17]:
arr[5:8]=12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [20]:
arr_slice=arr[5:8]
arr_slice

array([12, 12, 12])

In [21]:
arr_slice[1]=12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [29]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [31]:
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,     9])

In [32]:
arr[1:6]

array([ 1,  2,  3,  4, 12])

In [33]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
arr2d[:2,1:]=0
arr2d

array([[1, 0, 0],
       [4, 0, 0],
       [7, 8, 9]])

In [37]:
names=np.array(['bob','joe','amy','will','joe','joe'])
names

array(['bob', 'joe', 'amy', 'will', 'joe', 'joe'],
      dtype='<U4')

In [42]:
data=np.random.randn(7,4)
data

array([[ 0.44356376,  0.23834823,  1.75964071, -0.816435  ],
       [ 0.33129226,  0.99440816, -0.53890983,  0.38555713],
       [ 0.87907627,  1.9326231 ,  0.0252258 , -0.9888173 ],
       [-0.09892418, -0.39381868,  0.39009489, -0.10625563],
       [-0.45221707, -0.64088028, -0.61033866, -0.257644  ],
       [ 1.53470671,  0.52377208,  0.37229947,  0.53340916],
       [-0.8181572 , -0.54850336, -1.41724643,  2.14738042]])

In [43]:
names=='bob'

array([ True, False, False, False, False, False], dtype=bool)

In [44]:
names=np.array(['bob','joe','bob','amy','will','joe','joe'])
names=='bob'

array([ True, False,  True, False, False, False, False], dtype=bool)

In [46]:
data[names=='bob']

array([[ 0.44356376,  0.23834823,  1.75964071, -0.816435  ],
       [ 0.87907627,  1.9326231 ,  0.0252258 , -0.9888173 ]])

In [47]:
names!='bob'

array([False,  True, False,  True,  True,  True,  True], dtype=bool)

In [50]:
data[names!='bob']

array([[ 0.33129226,  0.99440816, -0.53890983,  0.38555713],
       [-0.09892418, -0.39381868,  0.39009489, -0.10625563],
       [-0.45221707, -0.64088028, -0.61033866, -0.257644  ],
       [ 1.53470671,  0.52377208,  0.37229947,  0.53340916],
       [-0.8181572 , -0.54850336, -1.41724643,  2.14738042]])

In [52]:
names

array(['bob', 'joe', 'bob', 'amy', 'will', 'joe', 'joe'],
      dtype='<U4')

In [55]:
mask=(names=='bob') | (names=='will')
mask

array([ True, False,  True, False,  True, False, False], dtype=bool)

In [56]:
data[mask]

array([[ 0.44356376,  0.23834823,  1.75964071, -0.816435  ],
       [ 0.87907627,  1.9326231 ,  0.0252258 , -0.9888173 ],
       [-0.45221707, -0.64088028, -0.61033866, -0.257644  ]])

In [59]:
data[mask]=0
data[mask]

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [60]:
data

array([[ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 0.33129226,  0.99440816, -0.53890983,  0.38555713],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [-0.09892418, -0.39381868,  0.39009489, -0.10625563],
       [ 0.        ,  0.        ,  0.        ,  0.        ],
       [ 1.53470671,  0.52377208,  0.37229947,  0.53340916],
       [-0.8181572 , -0.54850336, -1.41724643,  2.14738042]])

In [69]:
data=np.random.randn(7,4)
data

array([[ 0.10637506,  1.11172208, -0.07932079,  0.32034188],
       [-0.00368241, -0.50419881, -0.2015755 , -1.24667508],
       [-0.91097393,  0.65094909, -0.18372351,  0.74313584],
       [-0.50616428,  1.06675102,  0.44811135, -0.75651936],
       [ 0.7627202 ,  1.67636312, -0.45269131, -0.09015798],
       [-0.1472423 ,  1.89486445, -0.43762148,  2.08131879],
       [ 0.10615319,  0.36559578, -0.24438414,  0.17144033]])

In [71]:
data[names=='bob']=7
data

array([[  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [ -3.68241222e-03,  -5.04198807e-01,  -2.01575502e-01,
         -1.24667508e+00],
       [  7.00000000e+00,   7.00000000e+00,   7.00000000e+00,
          7.00000000e+00],
       [ -5.06164276e-01,   1.06675102e+00,   4.48111352e-01,
         -7.56519359e-01],
       [  7.62720197e-01,   1.67636312e+00,  -4.52691314e-01,
         -9.01579825e-02],
       [ -1.47242302e-01,   1.89486445e+00,  -4.37621482e-01,
          2.08131879e+00],
       [  1.06153189e-01,   3.65595781e-01,  -2.44384140e-01,
          1.71440331e-01]])

In [72]:
arr=np.empty((8,4))
arr

array([[  1.13093622e-311,   8.25057115e-315,   1.13093604e-311,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.13093618e-311],
       [  1.13090893e-311,   1.13092982e-311,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          0.00000000e+000],
       [  0.00000000e+000,   1.13088826e-311,   8.24930294e-315,
          1.13093621e-311],
       [  0.00000000e+000,   0.00000000e+000,   0.00000000e+000,
          1.13093606e-311],
       [  1.13093625e-311,   8.25055866e-315,   0.00000000e+000,
          0.00000000e+000],
       [  1.13093622e-311,   8.25055866e-315,   0.00000000e+000,
          8.25056293e-315]])

In [73]:
for i in range(8):
    arr[i]=i
arr

array([[ 0.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  1.],
       [ 2.,  2.,  2.,  2.],
       [ 3.,  3.,  3.,  3.],
       [ 4.,  4.,  4.,  4.],
       [ 5.,  5.,  5.,  5.],
       [ 6.,  6.,  6.,  6.],
       [ 7.,  7.,  7.,  7.]])

In [77]:
arr[[4,3,0,6]].shape

(4, 4)

In [78]:
arr=np.arange(32).reshape(8,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [79]:
arr[[1,5,7,2]]

array([[ 4,  5,  6,  7],
       [20, 21, 22, 23],
       [28, 29, 30, 31],
       [ 8,  9, 10, 11]])

In [80]:
arr[[1,5,7,2]][[0,3,1,2]]

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [20, 21, 22, 23],
       [28, 29, 30, 31]])

In [81]:
arr[[1,5,7,2]][:,[0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [82]:
arr[np.ix_([1,5,7,2],[0,3,1,2])]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [84]:
arr=np.arange(16).reshape((2,2,4))
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])