# 特征工程
[知乎@城东](https://www.zhihu.com/question/29316149)

### Jupyter Themes 配置
[Github](https://github.com/dunovank/jupyter-themes)

jt -t grade3 -T -N -f inconsolata -ofs 10

#### 修改关键字颜色
CSS File: C:\Users\your_name\.jupyter\custom\custom.css<br>
第2654行
```css
.cm-s-ipython span.cm-keyword {
 color: #66D971;  /*713bc5*/
 font-weight: bold;  /*normal*/
}
```
color: #66D971; weight: bold

# 2 数据预处理

In [3]:
from sklearn.datasets import load_iris

In [4]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [5]:
iris=load_iris()

In [6]:
data=DataFrame(iris.data,columns=['f1','f2','f3','f4'])
target=DataFrame(iris.target)

In [7]:
iris.data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

## 2.1 无量纲化

### 2.1.1 标准化

In [6]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(iris.data)[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### 2.1.2 区间缩放

In [7]:
from sklearn.preprocessing import MinMaxScaler

In [8]:
MinMaxScaler().fit_transform(iris.data)[:5]

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667],
       [ 0.08333333,  0.45833333,  0.08474576,  0.04166667],
       [ 0.19444444,  0.66666667,  0.06779661,  0.04166667]])

In [9]:
ss=DataFrame(iris.data)[0]
((ss-ss.min())/(ss.max()-ss.min()))[:5]

0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
Name: 0, dtype: float64

In [10]:
from sklearn.preprocessing import Normalizer

### 2.1.3 归一化
按行处理，每个元素除以一个和行中每个元素有关的数字：<br>
$ x^{'}=\frac{x}{\sqrt{\sum_{j}^{m}{x[j]^{2}}}} $

In [11]:
Normalizer().fit_transform(iris.data)[:5]

array([[ 0.80377277,  0.55160877,  0.22064351,  0.0315205 ],
       [ 0.82813287,  0.50702013,  0.23660939,  0.03380134],
       [ 0.80533308,  0.54831188,  0.2227517 ,  0.03426949],
       [ 0.80003025,  0.53915082,  0.26087943,  0.03478392],
       [ 0.790965  ,  0.5694948 ,  0.2214702 ,  0.0316386 ]])

## 2.2 定量特征二值化

In [12]:
from sklearn.preprocessing import Binarizer
Binarizer(threshold=3).fit_transform(iris.data)[:5]

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

## 2.3 哑编码

In [13]:
from sklearn.preprocessing import OneHotEncoder

In [21]:
one=OneHotEncoder().fit_transform(iris.target.reshape((-1,1)))
type(one)

scipy.sparse.csr.csr_matrix

## 2.4 缺失值计算

In [9]:
from numpy import vstack, array,nan
from sklearn.preprocessing import Imputer

In [32]:
Imputer().fit_transform(vstack((iris.data,array([nan,nan,nan,nan]))))[-5:]

array([[ 6.3       ,  2.5       ,  5.        ,  1.9       ],
       [ 6.5       ,  3.        ,  5.2       ,  2.        ],
       [ 6.2       ,  3.4       ,  5.4       ,  2.3       ],
       [ 5.9       ,  3.        ,  5.1       ,  1.8       ],
       [ 5.84333333,  3.054     ,  3.75866667,  1.19866667]])

## 2.5 数据变换

多项式转换，degress=2

In [34]:
from sklearn.preprocessing import PolynomialFeatures

$(x_1,x_2,x_3,x_4) → (1,x_1,x_2,x_3,x_4, x_1^2，x_1x_2,x_1x_3,x_1x_4,x_2^2,x_2x_3,x_2x_4,x_3^4,x_3x_4,x_4^2)$

In [37]:
PolynomialFeatures().fit_transform(iris.data)[0]

array([  1.  ,   5.1 ,   3.5 ,   1.4 ,   0.2 ,  26.01,  17.85,   7.14,
         1.02,  12.25,   4.9 ,   0.7 ,   1.96,   0.28,   0.04])

函数转换

In [39]:
from numpy import log1p   #log1p：
from sklearn.preprocessing import FunctionTransformer

In [42]:
FunctionTransformer(log1p).fit_transform(iris.data)[:3]

array([[ 1.80828877,  1.5040774 ,  0.87546874,  0.18232156],
       [ 1.77495235,  1.38629436,  0.87546874,  0.18232156],
       [ 1.74046617,  1.43508453,  0.83290912,  0.18232156]])

# 3 特征选择

## 3.1 Filter

### 3.1.1 方差选择

In [50]:
data.var()

f1    0.685694
f2    0.188004
f3    3.113179
f4    0.582414
dtype: float64

In [51]:
from sklearn.feature_selection import VarianceThreshold

In [63]:
VarianceThreshold(threshold=0.6).fit_transform(iris.data)[:3]   
#只剩下方差大于threshold的Feature，默认返回方差非零的Feature

array([[ 5.1,  1.4],
       [ 4.9,  1.4],
       [ 4.7,  1.3]])

### 3.3.2 相关系数选择

[皮尔森相关系数](https://baike.baidu.com/item/%E7%9A%AE%E5%B0%94%E6%A3%AE%E7%9B%B8%E5%85%B3%E7%B3%BB%E6%95%B0)

In [2]:
from scipy.stats import pearsonr
from sklearn.feature_selection import SelectKBest

In [10]:
SelectKBest(lambda X, Y: array(map(lambda x:pearsonr(x, Y), X.T)).T, k=2).fit_transform(iris.data, iris.target)

TypeError: float() argument must be a string or a number, not 'map'