# 特征工程
[知乎@城东](https://www.zhihu.com/question/29316149)

### Jupyter Themes 配置
[Github](https://github.com/dunovank/jupyter-themes)

jt -t grade3 -T -N -f inconsolata -ofs 10

#### 修改关键字颜色
CSS File: C:\Users\your_name\.jupyter\custom\custom.css<br>
第2654行
```css
.cm-s-ipython span.cm-keyword {
 color: #66D971;  /*713bc5*/
 font-weight: bold;  /*normal*/
}
```
color: #66D971; weight: bold

In [26]:
from sklearn.datasets import load_iris

In [27]:
import pandas as pd
from pandas import DataFrame,Series
import numpy as np

In [28]:
iris=load_iris()

In [50]:
iris.data[:5]

array([[ 5.1,  3.5,  1.4,  0.2],
       [ 4.9,  3. ,  1.4,  0.2],
       [ 4.7,  3.2,  1.3,  0.2],
       [ 4.6,  3.1,  1.5,  0.2],
       [ 5. ,  3.6,  1.4,  0.2]])

## 2.1 无量纲化

### 2.1.1 标准化

In [45]:
from sklearn.preprocessing import StandardScaler
StandardScaler().fit_transform(iris.data)[:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

### 2.1.2 区间缩放

In [12]:
from sklearn.preprocessing import MinMaxScaler

In [30]:
MinMaxScaler().fit_transform(iris.data)[:5]

array([[ 0.22222222,  0.625     ,  0.06779661,  0.04166667],
       [ 0.16666667,  0.41666667,  0.06779661,  0.04166667],
       [ 0.11111111,  0.5       ,  0.05084746,  0.04166667],
       [ 0.08333333,  0.45833333,  0.08474576,  0.04166667],
       [ 0.19444444,  0.66666667,  0.06779661,  0.04166667]])

In [44]:
ss=DataFrame(iris.data)[0]
((ss-ss.min())/(ss.max()-ss.min()))[:5]

0    0.222222
1    0.166667
2    0.111111
3    0.083333
4    0.194444
Name: 0, dtype: float64

In [52]:
from sklearn.preprocessing import Normalizer

### 2.1.3 归一化
按行处理，每个元素除以一个和行中每个元素有关的数字：<br>
$ x^{'}=\frac{x}{\sqrt{\sum_{j}^{m}{x[j]^{2}}}} $

In [47]:
Normalizer().fit_transform(iris.data)[:5]

array([[ 0.80377277,  0.55160877,  0.22064351,  0.0315205 ],
       [ 0.82813287,  0.50702013,  0.23660939,  0.03380134],
       [ 0.80533308,  0.54831188,  0.2227517 ,  0.03426949],
       [ 0.80003025,  0.53915082,  0.26087943,  0.03478392],
       [ 0.790965  ,  0.5694948 ,  0.2214702 ,  0.0316386 ]])

## 2.2 定量特征二值化

In [56]:
from sklearn.preprocessing import Binarizer
Binarizer(threshold=3).fit_transform(iris.data)[:5]

array([[ 1.,  1.,  0.,  0.],
       [ 1.,  0.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.],
       [ 1.,  1.,  0.,  0.]])

## 2.3 哑编码

In [57]:
from sklearn.preprocessing import OneHotEncoder

In [59]:
OneHotEncoder().fit_transform(iris.target.reshape((-1,1)))

<150x3 sparse matrix of type '<class 'numpy.float64'>'
	with 150 stored elements in Compressed Sparse Row format>

## 2.4 缺失值计算